-- Batch 3: Regulation-focused pages (10 pages)
INSERT INTO public.seo_pages (slug, meta_title, meta_description, h1_headline, page_type, is_published, priority, regulation_id, direct_answer_block, faq_items, content_sections, internal_links)
VALUES 
-- CBAM Compliance
('cbam-compliance-consulting', 'CBAM Compliance Consulting | Bombay Breed', 'Navigate EU Carbon Border Adjustment Mechanism. Reporting, embedded carbon calculations, and compliance strategies.', 'CBAM Compliance Consulting', 'regulation', true, 85, '777501c2-d3f7-4d5d-98a0-597af17ab2ca', 'CBAM requires quarterly reporting during transition (2023-2025) and carbon certificate purchases from 2026 for covered imports.', '[{"question": "When do CBAM payments start?", "answer": "January 2026, after transitional reporting phase."}, {"question": "How are costs calculated?", "answer": "Based on embedded emissions minus carbon price paid in origin country."}]', '{"introduction": "CBAM will add carbon costs to EU imports of steel, aluminium, cement, and more.", "main_content": "## Compliance Services\n\n### Reporting Setup\nTransitional phase quarterly reporting systems.\n\n### Carbon Calculation\nEmbedded emissions methodology."}', '[{"url": "/prepare-for-carbon-border-taxes", "title": "Prepare for CBAM"}]'),

-- PAT Scheme
('pat-scheme-consulting', 'PAT Scheme Consulting India | Bombay Breed', 'Navigate India''s PAT scheme. Energy audits, target achievement, and ESCert trading strategies.', 'PAT Scheme Consulting', 'regulation', true, 80, '50f52e0a-7a4a-415d-92fa-9525a810d6b6', 'PAT scheme sets specific energy consumption targets for designated consumers. Overachievement earns tradeable ESCerts.', '[{"question": "What sectors are covered?", "answer": "Cement, steel, aluminium, fertilizers, textiles, paper, chlor-alkali, and railways."}, {"question": "What are ESCerts worth?", "answer": "Market-determined price, historically Rs 200-1200 per tonne oil equivalent."}]', '{"introduction": "PAT scheme is India''s primary industrial energy efficiency regulation.", "main_content": "## Services\n\n### Target Assessment\nEvaluate baseline and targets.\n\n### Achievement Strategy\nCost-effective pathway to compliance."}', '[{"url": "/energy-optimisation-consulting-india", "title": "Energy Optimisation India"}]'),

-- Carbon Credit Trading Scheme
('ccts-compliance-india', 'India Carbon Credit Trading Scheme | Bombay Breed', 'Prepare for India''s domestic carbon market. Compliance readiness, trading strategies, and project development.', 'India Carbon Credit Trading Scheme Consulting', 'regulation', true, 80, '165bf45e-6ed6-46eb-81a7-2b0b97763642', 'India''s CCTS will create compliance carbon market starting 2025. Early preparation ensures cost-effective compliance.', '[{"question": "When does CCTS start?", "answer": "Phased implementation expected from 2025."}, {"question": "Which sectors are covered?", "answer": "Likely to start with power sector, expanding to heavy industry."}]', '{"introduction": "India is establishing its domestic carbon credit trading scheme.", "main_content": "## Readiness Services\n\n### Baseline Setting\nEmissions baseline for allocation.\n\n### Trading Strategy\nOptimal buy vs reduce decisions."}', '[{"url": "/article-6-consulting-india", "title": "Article 6 India"}]'),

-- Corresponding Adjustments
('corresponding-adjustments-consulting', 'Corresponding Adjustments Advisory | Bombay Breed', 'Navigate corresponding adjustments under Article 6. Bilateral agreements and authorization processes.', 'Corresponding Adjustments Advisory', 'regulation', true, 70, 'da4357ed-04fb-43a9-b962-aba30093ea0b', 'Corresponding adjustments ensure carbon credits are not double-counted between buyer and seller country NDCs.', '[{"question": "Why are CAs important?", "answer": "Without CAs, credits may be counted toward both countries'' NDCs."}, {"question": "Which countries offer CAs?", "answer": "Growing number including Singapore, Switzerland, and Japan have bilateral agreements."}]', '{"introduction": "Corresponding adjustments are critical for Article 6 credit integrity.", "main_content": "## Advisory Services\n\n### Country Assessment\nEvaluate CA availability by project location.\n\n### Authorization\nSupport obtaining host country authorization."}', '[{"url": "/article-6-consulting-india", "title": "Article 6 India"}]'),

-- Article 6 General
('article-6-compliance', 'Article 6 Compliance & Trading | Bombay Breed', 'Navigate Paris Agreement Article 6 mechanisms. Project development, trading, and compliance strategies.', 'Article 6 Compliance & Carbon Trading', 'regulation', true, 75, '2ccdbdf7-8095-4d38-a3da-c33afa1bc9bb', 'Article 6 enables international carbon trading through cooperative approaches (6.2) and crediting mechanism (6.4).', '[{"question": "What is Article 6.2 vs 6.4?", "answer": "6.2 is bilateral/cooperative approaches; 6.4 is UN-supervised crediting mechanism."}, {"question": "Which is more developed?", "answer": "6.2 bilateral deals are advancing faster than 6.4 operationalization."}]', '{"introduction": "Article 6 of the Paris Agreement creates new carbon market opportunities.", "main_content": "## Services\n\n### Project Development\nStructure projects for Article 6 compliance.\n\n### Trading Support\nConnect with buyers and negotiate transactions."}', '[{"url": "/article-6-consulting-india", "title": "Article 6 India"}]');