-- Batch 2: Geography × Capability combinations (20 pages)
INSERT INTO public.seo_pages (slug, meta_title, meta_description, h1_headline, page_type, is_published, priority, capability_id, geography_id, direct_answer_block, faq_items, content_sections, internal_links)
VALUES 
-- Energy Optimisation × India
('energy-optimisation-consulting-india', 'Energy Optimisation Consulting India | Bombay Breed', 'Expert energy optimization consulting for Indian industries. Reduce costs 15-30% through efficiency improvements and renewable integration.', 'Energy Optimisation Consulting in India', 'combined', true, 80, 'c3da7c4d-69ec-4ab8-a65c-a3ee6d902f19', '3cac1df6-093a-485b-9edf-75e569c36baf', 'India''s PAT scheme and rising energy costs make optimization essential. Expert consulting delivers 15-30% cost reduction with 2-4 year payback.', '[{"question": "What government incentives are available?", "answer": "PAT scheme ESCerts, accelerated depreciation, and state renewable incentives."}, {"question": "Which industries benefit most?", "answer": "Cement, steel, chemicals, textiles, and paper with high energy intensity."}]', '{"introduction": "Indian industries face rising energy costs and regulatory pressure under PAT scheme.", "main_content": "## Our Approach\n\n### Energy Audits\nDetailed audits identifying quick wins and strategic investments.\n\n### Implementation Support\nProject management and vendor selection."}', '[{"url": "/reduce-energy-costs-heavy-industry", "title": "Reduce Energy Costs"}]'),

-- Decarbonisation × India
('decarbonisation-consulting-india', 'Industrial Decarbonisation Consulting India | Bombay Breed', 'Strategic decarbonisation consulting for Indian industries. Net-zero pathways, technology roadmaps, and implementation support.', 'Industrial Decarbonisation Consulting in India', 'combined', true, 80, '8cdc4dc8-bbd6-4c58-a3bd-09b7cc8139d2', '3cac1df6-093a-485b-9edf-75e569c36baf', 'Indian industries must decarbonise for CBAM compliance and domestic carbon market readiness while maintaining competitiveness.', '[{"question": "Is decarbonisation mandatory in India?", "answer": "Voluntary now, but BRSR reporting and upcoming carbon market create strong drivers."}, {"question": "How does CBAM affect Indian exporters?", "answer": "Steel, aluminium, cement exporters to EU face carbon costs from 2026."}]', '{"introduction": "Indian industries face growing pressure from regulations and customer demands.", "main_content": "## Decarbonisation Services\n\n### Net-Zero Roadmaps\nScience-based pathways aligned with 1.5°C.\n\n### Technology Assessment\nEvaluate options from efficiency to hydrogen."}', '[{"url": "/prepare-for-carbon-border-taxes", "title": "Prepare for CBAM"}]'),

-- Decarbonisation × Gujarat
('decarbonisation-consulting-gujarat', 'Industrial Decarbonisation Consulting Gujarat | Bombay Breed', 'Decarbonisation strategies for Gujarat''s industrial clusters. Chemicals, ceramics, and textiles net-zero pathways.', 'Industrial Decarbonisation Consulting in Gujarat', 'combined', true, 70, '8cdc4dc8-bbd6-4c58-a3bd-09b7cc8139d2', '9c3b70fc-fb18-4046-9dff-215dfcf465b6', 'Gujarat''s chemical and ceramic industries need tailored decarbonisation strategies leveraging the state''s renewable potential.', '[{"question": "What is Gujarat''s renewable advantage?", "answer": "Excellent solar and wind resources, major RE capacity, and green hydrogen hub ambitions."}, {"question": "Which industries are priority?", "answer": "Chemicals, ceramics, textiles, and pharmaceuticals."}]', '{"introduction": "Gujarat''s industrial base faces decarbonisation imperatives.", "main_content": "## Industry Focus\n\n### Chemicals\nProcess electrification and hydrogen feedstock.\n\n### Ceramics\nKiln efficiency and fuel switching."}', '[{"url": "/energy-optimisation-consulting-gujarat", "title": "Energy Optimisation Gujarat"}]'),

-- Decarbonisation × Maharashtra
('decarbonisation-consulting-maharashtra', 'Industrial Decarbonisation Consulting Maharashtra | Bombay Breed', 'Decarbonisation strategies for Maharashtra industries. Automotive, chemicals, and steel net-zero pathways.', 'Industrial Decarbonisation Consulting in Maharashtra', 'combined', true, 70, '8cdc4dc8-bbd6-4c58-a3bd-09b7cc8139d2', '71aa7d95-9c88-4f5d-b773-e6a31059acbd', 'Maharashtra industries including automotive supply chains must decarbonise to meet OEM requirements and export standards.', '[{"question": "What drives decarbonisation in Maharashtra?", "answer": "OEM supply chain requirements, export compliance, and investor expectations."}, {"question": "Which sectors are priority?", "answer": "Automotive components, chemicals, steel, and textiles."}]', '{"introduction": "Maharashtra''s diverse industrial base requires sector-specific approaches.", "main_content": "## Sector Strategies\n\n### Automotive\nSupply chain decarbonisation for OEM compliance.\n\n### Chemicals\nProcess efficiency and renewable heat."}', '[{"url": "/energy-optimisation-consulting-maharashtra", "title": "Energy Optimisation Maharashtra"}]'),

-- Decarbonisation × UAE
('decarbonisation-consulting-uae', 'Industrial Decarbonisation Consulting UAE | Bombay Breed', 'Strategic decarbonisation consulting for UAE industries aligned with Net Zero 2050 vision.', 'Industrial Decarbonisation Consulting in UAE', 'combined', true, 75, '8cdc4dc8-bbd6-4c58-a3bd-09b7cc8139d2', 'dcb7efdf-cd45-4d50-af27-4031419b6cb8', 'UAE Net Zero 2050 requires industrial transformation. Expert consulting accelerates transition while maintaining competitiveness.', '[{"question": "What is UAE Net Zero 2050?", "answer": "National strategy to achieve carbon neutrality by 2050 through energy transition and industrial efficiency."}, {"question": "Which sectors are covered?", "answer": "Oil & gas, aluminium, steel, cement, and manufacturing."}]', '{"introduction": "UAE has committed to net zero by 2050, driving industrial transformation.", "main_content": "## Services\n\n### Strategy Development\nNet-zero roadmaps aligned with national targets.\n\n### Project Development\nBankable decarbonisation project pipelines."}', '[{"url": "/article-6-consulting-uae", "title": "Article 6 Consulting UAE"}]'),

-- Decarbonisation × Singapore
('decarbonisation-consulting-singapore', 'Industrial Decarbonisation Consulting Singapore | Bombay Breed', 'Decarbonisation strategies for Singapore industries. Petrochemicals, manufacturing, and data centres.', 'Industrial Decarbonisation Consulting in Singapore', 'combined', true, 75, '8cdc4dc8-bbd6-4c58-a3bd-09b7cc8139d2', 'ddb56910-e34d-4744-974f-4a1c3872d7e8', 'Singapore''s carbon tax and Green Plan 2030 drive industrial decarbonisation across petrochemicals and manufacturing.', '[{"question": "What is Singapore carbon tax rate?", "answer": "Rising from S$25/tCO2e in 2024 to S$50-80 by 2030."}, {"question": "Which sectors face highest exposure?", "answer": "Petrochemicals, power generation, and manufacturing."}]', '{"introduction": "Singapore''s rising carbon tax creates urgency for industrial decarbonisation.", "main_content": "## Focus Areas\n\n### Petrochemicals\nProcess efficiency and electrification.\n\n### Data Centres\nEnergy efficiency and renewable procurement."}', '[{"url": "/climate-investment-readiness-singapore", "title": "Climate Investment Readiness Singapore"}]'),

-- Climate Investment × India
('climate-investment-readiness-india', 'Climate Investment Readiness India | Bombay Breed', 'Prepare Indian companies for climate finance. Green bonds, transition finance, and DFI funding.', 'Climate Investment Readiness in India', 'combined', true, 75, '4a3007bc-d5a8-4e43-acba-640d1dd33e5f', '3cac1df6-093a-485b-9edf-75e569c36baf', 'India needs $10 trillion for net-zero transition. Investment readiness unlocks green bonds, DFI funding, and carbon finance.', '[{"question": "What climate finance is available in India?", "answer": "Green bonds, SIDBI facilities, DFI loans, and carbon credit financing."}, {"question": "What documentation is needed?", "answer": "Transition plans, ESG policies, and bankable project documentation."}]', '{"introduction": "Indian companies can access growing pool of climate capital.", "main_content": "## Readiness Services\n\n### Transition Planning\nCredible net-zero pathways for investors.\n\n### Project Structuring\nBankable documentation for funding."}', '[{"url": "/article-6-consulting-india", "title": "Article 6 Consulting India"}]'),

-- Climate Investment × Gujarat
('climate-investment-readiness-gujarat', 'Climate Investment Readiness Gujarat | Bombay Breed', 'Prepare Gujarat industries for climate finance and green investment opportunities.', 'Climate Investment Readiness in Gujarat', 'combined', true, 65, '4a3007bc-d5a8-4e43-acba-640d1dd33e5f', '9c3b70fc-fb18-4046-9dff-215dfcf465b6', 'Gujarat''s renewable energy hub status attracts climate investors. Readiness ensures companies capture opportunities.', '[{"question": "Why is Gujarat attractive for climate investment?", "answer": "Strong renewable resources, policy support, and industrial clusters."}, {"question": "What sectors attract investment?", "answer": "Renewables, green hydrogen, and industrial efficiency."}]', '{"introduction": "Gujarat is positioning as India''s green industrial hub.", "main_content": "## Investment Opportunities\n\n### Green Hydrogen\nEarly mover advantage in hydrogen ecosystem.\n\n### Industrial Clusters\nShared infrastructure opportunities."}', '[{"url": "/energy-optimisation-consulting-gujarat", "title": "Energy Optimisation Gujarat"}]'),

-- Climate Investment × Maharashtra
('climate-investment-readiness-maharashtra', 'Climate Investment Readiness Maharashtra | Bombay Breed', 'Prepare Maharashtra industries for climate finance and sustainable investment.', 'Climate Investment Readiness in Maharashtra', 'combined', true, 65, '4a3007bc-d5a8-4e43-acba-640d1dd33e5f', '71aa7d95-9c88-4f5d-b773-e6a31059acbd', 'Mumbai as India''s financial capital positions Maharashtra well for climate finance access.', '[{"question": "What is Maharashtra''s advantage?", "answer": "Access to financial institutions and investor networks."}, {"question": "Which sectors are priority?", "answer": "Manufacturing, automotive supply chains, and real estate."}]', '{"introduction": "Maharashtra combines industrial base with financial centre access.", "main_content": "## Investment Focus\n\n### Green Buildings\nReal estate sustainability investments.\n\n### Supply Chain\nAutomotive decarbonisation finance."}', '[{"url": "/decarbonisation-consulting-maharashtra", "title": "Decarbonisation Maharashtra"}]'),

-- Climate Investment × UAE
('climate-investment-readiness-uae', 'Climate Investment Readiness UAE | Bombay Breed', 'Prepare UAE companies for climate finance and sustainable investment opportunities.', 'Climate Investment Readiness in UAE', 'combined', true, 70, '4a3007bc-d5a8-4e43-acba-640d1dd33e5f', 'dcb7efdf-cd45-4d50-af27-4031419b6cb8', 'UAE''s sovereign wealth funds and green sukuk market offer significant climate finance opportunities.', '[{"question": "What green finance instruments exist?", "answer": "Green sukuk, sustainability-linked loans, and SWF investments."}, {"question": "How active are UAE investors?", "answer": "Masdar, ADIC, and Mubadala have major clean energy portfolios."}]', '{"introduction": "UAE is emerging as a climate finance hub for the region.", "main_content": "## Opportunities\n\n### Green Sukuk\nIslamic finance for clean energy.\n\n### SWF Capital\nAccess to sovereign wealth fund investments."}', '[{"url": "/decarbonisation-consulting-uae", "title": "Decarbonisation UAE"}]'),

-- Article 6 × Gujarat
('article-6-consulting-gujarat', 'Article 6 Carbon Credits Gujarat | Bombay Breed', 'Develop Article 6 carbon credit projects from Gujarat''s renewable and industrial projects.', 'Article 6 Carbon Credits in Gujarat', 'combined', true, 65, '9255d775-d68b-49bc-b4ab-e1fb5d9bfc64', '9c3b70fc-fb18-4046-9dff-215dfcf465b6', 'Gujarat''s renewable projects and industrial efficiency initiatives can generate high-value Article 6 credits.', '[{"question": "What Gujarat projects qualify?", "answer": "Renewable energy, industrial efficiency, and green hydrogen projects."}, {"question": "What is India''s Article 6 stance?", "answer": "India is developing bilateral agreements and domestic carbon market linkages."}]', '{"introduction": "Gujarat''s clean energy leadership creates Article 6 opportunities.", "main_content": "## Project Types\n\n### Renewables\nSolar and wind with additionality.\n\n### Industrial Efficiency\nPAT overachievement credits."}', '[{"url": "/article-6-consulting-india", "title": "Article 6 India"}]'),

-- Article 6 × Maharashtra
('article-6-consulting-maharashtra', 'Article 6 Carbon Credits Maharashtra | Bombay Breed', 'Develop Article 6 carbon credit projects from Maharashtra''s industrial decarbonisation.', 'Article 6 Carbon Credits in Maharashtra', 'combined', true, 65, '9255d775-d68b-49bc-b4ab-e1fb5d9bfc64', '71aa7d95-9c88-4f5d-b773-e6a31059acbd', 'Maharashtra industries can monetize emission reductions through Article 6 mechanisms.', '[{"question": "Which sectors have potential?", "answer": "Steel, cement, chemicals, and manufacturing efficiency."}, {"question": "How do credits complement domestic market?", "answer": "Article 6 offers additional revenue beyond CCTS."}]', '{"introduction": "Maharashtra''s industrial base offers significant Article 6 potential.", "main_content": "## Opportunities\n\n### Industrial Efficiency\nEnergy optimization projects.\n\n### Fuel Switching\nBiomass and alternative fuel credits."}', '[{"url": "/article-6-consulting-india", "title": "Article 6 India"}]'),

-- DMRV × India
('dmrv-consulting-india', 'MRV & Carbon Accounting India | Bombay Breed', 'Implement robust MRV systems for Indian companies. BRSR compliance, carbon accounting, and verification.', 'MRV & Carbon Accounting Services in India', 'combined', true, 70, '7ee0fc75-660c-40ac-b13b-e5079b30735d', '3cac1df6-093a-485b-9edf-75e569c36baf', 'Indian companies need MRV systems for BRSR reporting, carbon market participation, and export compliance.', '[{"question": "Is MRV mandatory in India?", "answer": "BRSR Core requires emission reporting for top 1000 companies."}, {"question": "What standards apply?", "answer": "GHG Protocol, BRSR format, and IS0 14064 for verification."}]', '{"introduction": "Robust MRV is foundational for sustainability claims and market participation.", "main_content": "## Services\n\n### GHG Inventories\nScope 1, 2, 3 accounting per GHG Protocol.\n\n### BRSR Reporting\nCompliance with SEBI disclosure requirements."}', '[{"url": "/measure-scope-3-emissions", "title": "Measure Scope 3 Emissions"}]'),

-- DMRV × UAE
('dmrv-consulting-uae', 'MRV & Carbon Accounting UAE | Bombay Breed', 'Implement MRV systems for UAE companies aligned with national reporting requirements.', 'MRV & Carbon Accounting Services in UAE', 'combined', true, 65, '7ee0fc75-660c-40ac-b13b-e5079b30735d', 'dcb7efdf-cd45-4d50-af27-4031419b6cb8', 'UAE companies need robust MRV for national GHG inventory and Net Zero 2050 tracking.', '[{"question": "What reporting is required?", "answer": "Mandatory reporting for large emitters under national framework."}, {"question": "How does this support Net Zero 2050?", "answer": "Accurate tracking enables credible progress measurement."}]', '{"introduction": "MRV underpins UAE''s Net Zero 2050 accountability.", "main_content": "## Services\n\n### Corporate Inventories\nFacility and enterprise-level accounting.\n\n### Verification\nThird-party assurance for credibility."}', '[{"url": "/decarbonisation-consulting-uae", "title": "Decarbonisation UAE"}]'),

-- DMRV × Singapore
('dmrv-consulting-singapore', 'MRV & Carbon Accounting Singapore | Bombay Breed', 'Implement MRV systems for Singapore companies. Carbon tax reporting and verification.', 'MRV & Carbon Accounting Services in Singapore', 'combined', true, 65, '7ee0fc75-660c-40ac-b13b-e5079b30735d', 'ddb56910-e34d-4744-974f-4a1c3872d7e8', 'Singapore carbon tax requires accurate MRV for tax liability calculation and international carbon credit use.', '[{"question": "What are carbon tax MRV requirements?", "answer": "Annual emissions reporting with third-party verification for taxable facilities."}, {"question": "Can international credits offset tax?", "answer": "Yes, up to 5% of liability with approved credits."}]', '{"introduction": "Singapore''s carbon tax creates mandatory MRV requirements.", "main_content": "## Services\n\n### Tax Reporting\nCompliant emissions calculations.\n\n### Credit Eligibility\nVerification for offset credit use."}', '[{"url": "/decarbonisation-consulting-singapore", "title": "Decarbonisation Singapore"}]'),

-- Energy Optimisation × UAE
('energy-optimisation-consulting-uae', 'Energy Optimisation Consulting UAE | Bombay Breed', 'Energy efficiency consulting for UAE industries supporting Net Zero 2050 goals.', 'Energy Optimisation Consulting in UAE', 'combined', true, 70, 'c3da7c4d-69ec-4ab8-a65c-a3ee6d902f19', 'dcb7efdf-cd45-4d50-af27-4031419b6cb8', 'UAE industries can achieve 20-30% energy savings through optimization while supporting national Net Zero 2050 targets.', '[{"question": "What drives energy efficiency in UAE?", "answer": "Rising costs, sustainability mandates, and Net Zero 2050 requirements."}, {"question": "Which sectors have highest potential?", "answer": "Oil & gas, manufacturing, and buildings."}]', '{"introduction": "Energy efficiency is the first step in UAE''s decarbonisation journey.", "main_content": "## Focus Areas\n\n### Industrial Processes\nOptimization and waste heat recovery.\n\n### Building Systems\nHVAC and lighting efficiency."}', '[{"url": "/decarbonisation-consulting-uae", "title": "Decarbonisation UAE"}]'),

-- Energy Optimisation × Singapore
('energy-optimisation-consulting-singapore', 'Energy Optimisation Consulting Singapore | Bombay Breed', 'Energy efficiency consulting for Singapore industries. Reduce costs and carbon tax liability.', 'Energy Optimisation Consulting in Singapore', 'combined', true, 70, 'c3da7c4d-69ec-4ab8-a65c-a3ee6d902f19', 'ddb56910-e34d-4744-974f-4a1c3872d7e8', 'Singapore carbon tax makes energy efficiency highly economical with additional S$25-80/tCO2 savings.', '[{"question": "How does carbon tax affect economics?", "answer": "Adds S$25-80/tCO2 to energy efficiency payback calculations."}, {"question": "What are priority sectors?", "answer": "Petrochemicals, data centres, and manufacturing."}]', '{"introduction": "Singapore''s carbon tax creates strong incentives for energy efficiency.", "main_content": "## Services\n\n### Energy Audits\nIdentify efficiency opportunities.\n\n### Carbon Tax Optimization\nMinimize tax liability through efficiency."}', '[{"url": "/decarbonisation-consulting-singapore", "title": "Decarbonisation Singapore"}]');