-- Batch 4: Additional problem-led and cross-cutting pages (15 pages)
INSERT INTO public.seo_pages (slug, meta_title, meta_description, h1_headline, page_type, is_published, priority, direct_answer_block, faq_items, content_sections, internal_links)
VALUES 
-- Problem-led pages
('net-zero-strategy-manufacturing', 'Net Zero Strategy for Manufacturing | Bombay Breed', 'Develop credible net-zero strategies for manufacturing companies. Science-based targets, roadmaps, and implementation.', 'Net Zero Strategy for Manufacturing', 'problem', true, 80, 'Manufacturing net-zero requires emissions baseline, science-based targets, technology roadmap, and phased implementation across Scope 1, 2, and 3.', '[{"question": "What is a science-based target?", "answer": "Emissions reduction aligned with 1.5°C or well-below 2°C pathways per SBTi."}, {"question": "How long does net-zero planning take?", "answer": "Strategy development typically 3-6 months; implementation is multi-year."}]', '{"introduction": "Manufacturing companies face growing pressure to commit to net-zero.", "main_content": "## Strategy Components\n\n### Baseline\nComprehensive Scope 1, 2, 3 inventory.\n\n### Target Setting\nSBTi-aligned near and long-term targets.\n\n### Roadmap\nTechnology and investment pathway."}', '[{"url": "/measure-scope-3-emissions", "title": "Measure Scope 3 Emissions"}]'),

('carbon-footprint-supply-chain', 'Supply Chain Carbon Footprint Reduction | Bombay Breed', 'Measure and reduce supply chain carbon footprint. Supplier engagement, Scope 3 accounting, and procurement strategies.', 'Supply Chain Carbon Footprint Reduction', 'problem', true, 75, 'Supply chain emissions (Scope 3) typically represent 70-90% of total footprint. Reduction requires supplier engagement and procurement changes.', '[{"question": "How do I measure supply chain emissions?", "answer": "Through supplier data collection, spend-based estimates, or hybrid approaches."}, {"question": "What levers reduce supply chain emissions?", "answer": "Supplier engagement, low-carbon procurement, and product redesign."}]', '{"introduction": "Supply chain decarbonisation is essential for meaningful climate action.", "main_content": "## Approach\n\n### Mapping\nIdentify emission hotspots in supply chain.\n\n### Engagement\nWork with key suppliers on reduction.\n\n### Procurement\nIntegrate carbon criteria in sourcing."}', '[{"url": "/measure-scope-3-emissions", "title": "Measure Scope 3 Emissions"}]'),

('renewable-energy-procurement-india', 'Renewable Energy Procurement India | Bombay Breed', 'Source renewable energy for your operations. Open access, captive, group captive, and PPA options in India.', 'Renewable Energy Procurement in India', 'problem', true, 75, 'Indian companies can source renewables through captive projects, open access, group captive, or virtual PPAs with 15-40% cost savings.', '[{"question": "What is open access renewable energy?", "answer": "Purchasing power from off-site renewable projects through grid wheeling."}, {"question": "What savings are possible?", "answer": "15-40% compared to grid tariffs depending on state and structure."}]', '{"introduction": "Renewable energy procurement is the fastest route to Scope 2 reduction.", "main_content": "## Procurement Options\n\n### Captive\nOwn renewable projects on-site or off-site.\n\n### Open Access\nThird-party PPAs with grid wheeling.\n\n### RECs\nRenewable energy certificates for attribution."}', '[{"url": "/energy-optimisation-consulting-india", "title": "Energy Optimisation India"}]'),

('green-hydrogen-strategy', 'Green Hydrogen Strategy & Advisory | Bombay Breed', 'Develop green hydrogen strategies for producers and consumers. Technology assessment, project development, and offtake.', 'Green Hydrogen Strategy & Advisory', 'problem', true, 75, 'Green hydrogen is produced from renewable electricity via electrolysis. Key applications include ammonia, steel, refining, and transport.', '[{"question": "What is the current cost of green hydrogen?", "answer": "Currently $4-6/kg, expected to reach $1-2/kg by 2030 in optimal locations."}, {"question": "Where is green hydrogen most viable?", "answer": "Gujarat, Rajasthan, and southern states with low RE costs."}]', '{"introduction": "Green hydrogen is emerging as key decarbonisation pathway for hard-to-abate sectors.", "main_content": "## Services\n\n### Strategy\nAssess hydrogen opportunities in your value chain.\n\n### Project Development\nSupport hydrogen production project development."}', '[{"url": "/climate-investment-readiness", "title": "Climate Investment Readiness"}]'),

('carbon-credit-due-diligence', 'Carbon Credit Due Diligence | Bombay Breed', 'Ensure carbon credit quality and integrity. Project assessment, registry verification, and risk analysis.', 'Carbon Credit Due Diligence', 'problem', true, 70, 'Carbon credit due diligence assesses additionality, permanence, leakage, and verification to ensure offset quality and avoid greenwashing risks.', '[{"question": "What makes a quality carbon credit?", "answer": "Real, additional, permanent, verified, and not double-counted."}, {"question": "What are common quality issues?", "answer": "Additionality concerns, overestimated baselines, and reversal risks."}]', '{"introduction": "Carbon credit quality varies significantly. Due diligence protects reputation and ensures impact.", "main_content": "## Assessment Framework\n\n### Additionality\nWould the project happen without carbon finance?\n\n### Permanence\nAre emission reductions permanent or reversible?"}', '[{"url": "/dmrv-integrity-due-diligence", "title": "DMRV Integrity Due Diligence"}]'),

('sustainability-reporting-brsr', 'BRSR Sustainability Reporting India | Bombay Breed', 'Navigate BRSR Core and comprehensive reporting requirements. GHG inventories, ESG disclosures, and assurance.', 'BRSR Sustainability Reporting', 'problem', true, 75, 'BRSR requires listed companies to report ESG metrics including GHG emissions, energy consumption, and social indicators annually.', '[{"question": "Who must comply with BRSR?", "answer": "Top 1000 listed companies by market cap for comprehensive; BRSR Core for top 150."}, {"question": "What GHG reporting is required?", "answer": "Scope 1, 2, and increasingly Scope 3 emissions with intensity metrics."}]', '{"introduction": "SEBI''s BRSR framework is India''s primary sustainability disclosure requirement.", "main_content": "## Reporting Services\n\n### GHG Inventory\nScope 1, 2, 3 calculations per GHG Protocol.\n\n### ESG Metrics\nSocial and governance indicators.\n\n### Assurance\nThird-party verification support."}', '[{"url": "/measure-scope-3-emissions", "title": "Measure Scope 3 Emissions"}]'),

('transition-risk-assessment', 'Climate Transition Risk Assessment | Bombay Breed', 'Assess climate transition risks for your business. Policy, technology, market, and reputation risk analysis.', 'Climate Transition Risk Assessment', 'problem', true, 70, 'Transition risks arise from policy changes, technology shifts, market dynamics, and reputation concerns as economy decarbonises.', '[{"question": "What are key transition risk types?", "answer": "Policy and legal, technology, market, and reputation risks."}, {"question": "How is transition risk assessed?", "answer": "Scenario analysis examining impact of different decarbonisation pathways on business."}]', '{"introduction": "Climate transition creates both risks and opportunities for businesses.", "main_content": "## Assessment Framework\n\n### Policy Risk\nCarbon pricing, regulations, and standards.\n\n### Technology Risk\nDisruption from low-carbon alternatives.\n\n### Market Risk\nChanging customer and investor preferences."}', '[{"url": "/climate-investment-readiness", "title": "Climate Investment Readiness"}]'),

('industrial-waste-heat-recovery', 'Industrial Waste Heat Recovery | Bombay Breed', 'Capture and utilize waste heat from industrial processes. Technology options, project development, and financing.', 'Industrial Waste Heat Recovery', 'problem', true, 70, 'Waste heat recovery can capture 20-50% of thermal energy losses for power generation or process heating with 3-5 year payback.', '[{"question": "What temperatures are recoverable?", "answer": "High (>400°C), medium (150-400°C), and low (<150°C) grade heat have different technologies."}, {"question": "What are typical payback periods?", "answer": "2-5 years depending on heat grade and application."}]', '{"introduction": "Industrial processes waste significant thermal energy that can be recovered.", "main_content": "## Technologies\n\n### ORC Systems\nOrganic Rankine Cycle for medium-grade heat power.\n\n### Heat Exchangers\nProcess-to-process heat recovery.\n\n### Heat Pumps\nUpgrade low-grade heat for useful applications."}', '[{"url": "/reduce-energy-costs-heavy-industry", "title": "Reduce Energy Costs"}]'),

('electric-vehicle-fleet-transition', 'EV Fleet Transition Strategy | Bombay Breed', 'Plan and execute commercial fleet electrification. TCO analysis, charging infrastructure, and implementation.', 'Electric Vehicle Fleet Transition', 'problem', true, 65, 'Commercial EV fleets can achieve 30-50% lower TCO than diesel while eliminating tailpipe emissions.', '[{"question": "When is EV fleet economical?", "answer": "Now for urban delivery; 2025-27 for intercity and heavier vehicles."}, {"question": "What infrastructure is needed?", "answer": "Depot charging, route charging for long-haul, and grid connection upgrades."}]', '{"introduction": "Fleet electrification is accelerating as EV economics improve.", "main_content": "## Transition Planning\n\n### TCO Analysis\nCompare EV vs conventional total cost.\n\n### Phasing\nPrioritize vehicles and routes for transition.\n\n### Infrastructure\nPlan charging deployment."}', '[{"url": "/decarbonisation-consulting-india", "title": "Decarbonisation India"}]'),

('corporate-renewable-ppa', 'Corporate Renewable PPA Advisory | Bombay Breed', 'Structure and negotiate renewable power purchase agreements. Physical, virtual, and sleeved PPA options.', 'Corporate Renewable PPA Advisory', 'problem', true, 70, 'Corporate PPAs provide price certainty, renewable claims, and often cost savings for 10-25 year terms.', '[{"question": "What PPA structures exist?", "answer": "Physical (on-site/off-site), virtual (financial), and sleeved arrangements."}, {"question": "What contract terms matter?", "answer": "Price, tenor, settlement mechanism, and renewable attribute treatment."}]', '{"introduction": "Corporate PPAs enable direct renewable procurement with long-term benefits.", "main_content": "## Services\n\n### Structuring\nDesign optimal PPA structure.\n\n### Negotiation\nSupport developer selection and terms.\n\n### Execution\nTransaction management through signing."}', '[{"url": "/renewable-energy-procurement-india", "title": "Renewable Procurement India"}]'),

('internal-carbon-pricing', 'Internal Carbon Pricing Strategy | Bombay Breed', 'Implement internal carbon pricing to drive decarbonisation decisions. Shadow pricing, fee systems, and governance.', 'Internal Carbon Pricing Strategy', 'problem', true, 65, 'Internal carbon pricing embeds carbon costs in business decisions at $25-100/tCO2 to drive investment toward low-carbon options.', '[{"question": "What price should we set?", "answer": "Typically $25-100/tCO2 based on regulatory expectations and abatement costs."}, {"question": "What are implementation options?", "answer": "Shadow pricing for decisions, internal fee collected and reinvested, or implicit pricing in project hurdles."}]', '{"introduction": "Internal carbon pricing prepares companies for external carbon costs.", "main_content": "## Implementation\n\n### Price Setting\nDetermine appropriate price level.\n\n### Governance\nDefine scope and application rules.\n\n### Revenue Use\nDirect internal carbon revenue to decarbonisation."}', '[{"url": "/climate-investment-readiness", "title": "Climate Investment Readiness"}]'),

('science-based-targets', 'Science-Based Targets Advisory | Bombay Breed', 'Set and achieve science-based emissions reduction targets. SBTi alignment, near-term and net-zero targets.', 'Science-Based Targets Advisory', 'problem', true, 75, 'Science-based targets align corporate emissions reduction with Paris Agreement goals. SBTi validates targets against 1.5°C pathways.', '[{"question": "What is SBTi?", "answer": "Science Based Targets initiative that validates corporate climate targets."}, {"question": "What targets are required?", "answer": "Near-term (5-10 year) emissions cuts and long-term net-zero commitment."}]', '{"introduction": "Science-based targets demonstrate credible climate commitment.", "main_content": "## Services\n\n### Target Development\nSet ambitious yet achievable SBTi-aligned targets.\n\n### Validation Support\nNavigate SBTi submission process.\n\n### Implementation\nDevelop roadmap to achieve targets."}', '[{"url": "/net-zero-strategy-manufacturing", "title": "Net Zero for Manufacturing"}]'),

('carbon-neutral-certification', 'Carbon Neutral Certification | Bombay Breed', 'Achieve carbon neutral certification for products, sites, or organizations. Methodology, verification, and communication.', 'Carbon Neutral Certification', 'problem', true, 65, 'Carbon neutrality requires measuring emissions, reducing where possible, and offsetting remainder with quality credits.', '[{"question": "What standards exist?", "answer": "PAS 2060, Climate Active, and various registry-specific standards."}, {"question": "What is the process?", "answer": "Inventory, reduction plan, offset purchase, verification, and certification."}]', '{"introduction": "Carbon neutral certification provides credible climate claim.", "main_content": "## Certification Process\n\n### Boundary Setting\nDefine what is covered by claim.\n\n### Reduction\nImplement emission reduction measures.\n\n### Offsetting\nProcure quality credits for residual emissions."}', '[{"url": "/carbon-credit-due-diligence", "title": "Carbon Credit Due Diligence"}]'),

('climate-disclosure-tcfd', 'TCFD Climate Disclosure | Bombay Breed', 'Implement TCFD-aligned climate risk disclosure. Governance, strategy, risk management, and metrics.', 'TCFD Climate Disclosure', 'problem', true, 70, 'TCFD provides framework for climate risk disclosure covering governance, strategy, risk management, and metrics/targets.', '[{"question": "Is TCFD mandatory?", "answer": "Increasingly required by regulators, investors, and customers globally."}, {"question": "What scenarios are used?", "answer": "Typically 1.5°C, 2°C, and 4°C warming scenarios for risk assessment."}]', '{"introduction": "TCFD is becoming the global standard for climate disclosure.", "main_content": "## Implementation\n\n### Governance\nBoard and management climate oversight.\n\n### Scenario Analysis\nAssess risks under different climate pathways.\n\n### Metrics\nEmissions, targets, and risk indicators."}', '[{"url": "/transition-risk-assessment", "title": "Transition Risk Assessment"}]'),

('green-building-certification', 'Green Building Certification India | Bombay Breed', 'Achieve green building certification. IGBC, GRIHA, LEED, and EDGE certification support.', 'Green Building Certification', 'problem', true, 60, 'Green building certification reduces operational costs 20-30% while improving occupant health and market value.', '[{"question": "Which certification should I choose?", "answer": "IGBC and GRIHA for India context; LEED for international recognition."}, {"question": "What are key requirements?", "answer": "Energy efficiency, water conservation, materials, and indoor environment quality."}]', '{"introduction": "Green buildings deliver environmental and economic benefits.", "main_content": "## Certification Support\n\n### Pre-certification\nDesign review and gap analysis.\n\n### Documentation\nPrepare submission materials.\n\n### Commissioning\nVerify performance meets requirements."}', '[{"url": "/energy-optimisation-consulting-india", "title": "Energy Optimisation India"}]');