-- Batch 1: Capability × Industry combinations (12 pages)
INSERT INTO public.seo_pages (slug, meta_title, meta_description, h1_headline, page_type, is_published, priority, capability_id, industry_id, direct_answer_block, faq_items, content_sections, internal_links)
VALUES 
-- Energy Optimisation × Oil & Gas
('energy-optimisation-oil-gas', 'Energy Optimisation for Oil & Gas | Bombay Breed', 'Reduce energy costs and emissions in oil & gas operations through process optimization, waste heat recovery, and renewable integration.', 'Energy Optimisation for Oil & Gas Sector', 'combined', true, 75, 'c3da7c4d-69ec-4ab8-a65c-a3ee6d902f19', '1ad6b943-c121-48c0-8e87-16a19d529241', 'Oil & gas companies can reduce energy consumption by 15-25% through flare gas recovery, waste heat utilization, and process optimization.', '[{"question": "What are the biggest energy efficiency opportunities in oil & gas?", "answer": "Flare gas recovery, compressor optimization, waste heat recovery, and electrification offer the highest potential."}, {"question": "How does energy optimization reduce emissions?", "answer": "Lower energy consumption directly reduces Scope 1 and 2 emissions."}]', '{"introduction": "The oil & gas sector faces pressure to reduce energy intensity while maintaining efficiency.", "main_content": "## Key Optimization Areas\n\n### Flare Gas Recovery\nCapture and monetize flare gas.\n\n### Compressor Efficiency\nOptimize compressor operations.\n\n### Waste Heat Recovery\nUtilize thermal energy from processes."}', '[{"url": "/industrial-decarbonisation-strategy", "title": "Industrial Decarbonisation Strategy"}]'),

-- Energy Optimisation × Power Sector
('energy-optimisation-power-sector', 'Energy Optimisation for Power Sector | Bombay Breed', 'Improve power plant efficiency and reduce auxiliary consumption for thermal and renewable power generators.', 'Energy Optimisation for Power Sector', 'combined', true, 75, 'c3da7c4d-69ec-4ab8-a65c-a3ee6d902f19', '259065e1-e63b-4a45-9b1e-270eca994b7e', 'Power plants can improve efficiency by 2-5% through combustion optimization, auxiliary power reduction, and advanced controls.', '[{"question": "What is auxiliary power consumption?", "answer": "Energy consumed by plant equipment, typically 5-10% of gross generation."}, {"question": "How can thermal plants improve efficiency?", "answer": "Through combustion optimization, condenser cleaning, and VFDs on auxiliaries."}]', '{"introduction": "Power generation efficiency directly impacts profitability and emissions intensity.", "main_content": "## Efficiency Strategies\n\n### Heat Rate Optimization\nTarget 1-3% improvement through tuning.\n\n### Auxiliary Power Reduction\nImplement VFDs on fans and pumps."}', '[{"url": "/reduce-energy-costs-heavy-industry", "title": "Reduce Energy Costs"}]'),

-- Decarbonisation × Cement
('decarbonisation-cement-industry', 'Decarbonisation for Cement Industry | Bombay Breed', 'Comprehensive decarbonisation strategies for cement including alternative fuels, clinker substitution, and carbon capture.', 'Decarbonisation Strategies for Cement Industry', 'combined', true, 80, '8cdc4dc8-bbd6-4c58-a3bd-09b7cc8139d2', 'c8355272-2a85-49c6-9ba8-2145924d2daf', 'Cement decarbonisation requires alternative fuels (20-30% reduction), clinker substitution (10-15%), and CCUS for process emissions.', '[{"question": "Why is cement difficult to decarbonise?", "answer": "60% of emissions come from calcination, not fuel combustion."}, {"question": "What are alternative fuels for cement kilns?", "answer": "RDF, biomass, industrial waste, and used tires."}]', '{"introduction": "Cement accounts for 7-8% of global CO2 emissions. Decarbonisation is essential for climate goals.", "main_content": "## Decarbonisation Levers\n\n### Alternative Fuels\nReplace coal with waste-derived fuels.\n\n### Clinker Substitution\nIncrease fly ash and slag use.\n\n### Carbon Capture\nDeploy CCUS for process emissions."}', '[{"url": "/energy-optimisation-cement-industry", "title": "Energy Optimisation for Cement"}]'),

-- Decarbonisation × Oil & Gas
('decarbonisation-oil-gas', 'Decarbonisation for Oil & Gas | Bombay Breed', 'Navigate the energy transition with methane reduction, electrification, and renewable diversification strategies.', 'Decarbonisation Strategies for Oil & Gas', 'combined', true, 80, '8cdc4dc8-bbd6-4c58-a3bd-09b7cc8139d2', '1ad6b943-c121-48c0-8e87-16a19d529241', 'Oil & gas decarbonisation focuses on methane LDAR, flare reduction, electrification, and diversification into hydrogen and renewables.', '[{"question": "What is the biggest near-term opportunity?", "answer": "Methane reduction through LDAR can cut 30-50% of upstream emissions."}, {"question": "How are O&G companies diversifying?", "answer": "Investments in renewables, hydrogen, carbon capture, and biofuels."}]', '{"introduction": "The oil & gas sector faces existential questions as the energy transition accelerates.", "main_content": "## Transition Strategies\n\n### Methane Management\nImplement comprehensive LDAR programs.\n\n### Electrification\nReplace gas-driven equipment.\n\n### Portfolio Diversification\nInvest in renewables and hydrogen."}', '[{"url": "/energy-optimisation-oil-gas", "title": "Energy Optimisation for Oil & Gas"}]'),

-- Decarbonisation × Power
('decarbonisation-power-sector', 'Decarbonisation for Power Sector | Bombay Breed', 'Power sector transition with renewable integration, storage, and coal retirement planning.', 'Decarbonisation Strategies for Power Sector', 'combined', true, 80, '8cdc4dc8-bbd6-4c58-a3bd-09b7cc8139d2', '259065e1-e63b-4a45-9b1e-270eca994b7e', 'Power sector decarbonisation requires renewable capacity addition, coal retirement planning, and storage deployment.', '[{"question": "What is the role of coal plants in transition?", "answer": "Gradual retirement with just transition support."}, {"question": "How much storage is needed?", "answer": "India targets 27 GW of battery storage by 2030."}]', '{"introduction": "The power sector is central to economy-wide decarbonisation.", "main_content": "## Transition Pathways\n\n### Renewable Expansion\nScale solar, wind, and hybrid projects.\n\n### Storage Deployment\nBattery and pumped hydro for flexibility.\n\n### Grid Modernisation\nSmart grid investments."}', '[{"url": "/energy-optimisation-power-sector", "title": "Energy Optimisation for Power"}]'),

-- Decarbonisation × Data Centres
('decarbonisation-data-centres', 'Decarbonisation for Data Centres | Bombay Breed', 'Sustainable data centre strategies including renewable procurement and cooling efficiency.', 'Decarbonisation Strategies for Data Centres', 'combined', true, 75, '8cdc4dc8-bbd6-4c58-a3bd-09b7cc8139d2', 'd9f976b1-c2a7-48e1-bf3c-1cd6e805b04e', 'Data centres can achieve carbon neutrality through 100% renewable procurement and PUE optimization below 1.4.', '[{"question": "What is PUE?", "answer": "Power Usage Effectiveness measures facility power vs IT load. Best-in-class achieve 1.2-1.3."}, {"question": "How can data centres source renewables?", "answer": "Captive solar, open access, or certificates."}]', '{"introduction": "Data centres are among the fastest-growing energy consumers.", "main_content": "## Sustainability Strategies\n\n### Renewable Energy\n100% renewable through PPAs or captive.\n\n### Cooling Efficiency\nFree cooling and liquid cooling."}', '[{"url": "/energy-efficiency-data-centres", "title": "Energy Efficiency for Data Centres"}]'),

-- Article 6 × Steel
('article-6-steel-industry', 'Article 6 Carbon Credits for Steel Industry | Bombay Breed', 'Generate carbon credits from steel decarbonisation projects under Article 6.', 'Article 6 Carbon Credits for Steel Industry', 'combined', true, 70, '9255d775-d68b-49bc-b4ab-e1fb5d9bfc64', '635fa88b-ef75-4f99-b3e8-30e51331c6df', 'Steel decarbonisation projects can generate Article 6 credits worth $10-30 per tonne CO2.', '[{"question": "What steel projects qualify for Article 6?", "answer": "Energy efficiency, fuel switching, hydrogen-DRI, and CCUS projects."}, {"question": "What is credit value?", "answer": "High-integrity credits fetch $15-50."}]', '{"introduction": "Article 6 creates opportunities for steel companies to monetize emission reductions.", "main_content": "## Credit Opportunities\n\n### Eligible Projects\nEnergy efficiency, fuel switching, hydrogen-DRI.\n\n### Revenue Potential\n$10-30 per tonne CO2."}', '[{"url": "/decarbonisation-steel-industry", "title": "Decarbonisation for Steel"}]'),

-- Article 6 × Cement
('article-6-cement-industry', 'Article 6 Carbon Credits for Cement Industry | Bombay Breed', 'Develop Article 6 credits from cement decarbonisation projects.', 'Article 6 Carbon Credits for Cement Industry', 'combined', true, 70, '9255d775-d68b-49bc-b4ab-e1fb5d9bfc64', 'c8355272-2a85-49c6-9ba8-2145924d2daf', 'Cement industry can generate credits from alternative fuel switching and clinker ratio reduction.', '[{"question": "Can process emissions generate credits?", "answer": "Yes, CCUS projects can generate credits."}, {"question": "What documentation is required?", "answer": "PDD, baseline study, monitoring plan, and verification."}]', '{"introduction": "Cement''s hard-to-abate emissions make it priority for Article 6 mechanisms.", "main_content": "## Credit Pathways\n\n### Alternative Fuels\nSwitching from coal to waste-derived fuels.\n\n### Carbon Capture\nCCUS on process emissions."}', '[{"url": "/decarbonisation-cement-industry", "title": "Decarbonisation for Cement"}]'),

-- Climate Investment × Steel
('climate-investment-steel', 'Climate Investment for Steel Industry | Bombay Breed', 'Prepare steel companies for climate finance with bankable project development.', 'Climate Investment Readiness for Steel Industry', 'combined', true, 70, '4a3007bc-d5a8-4e43-acba-640d1dd33e5f', '635fa88b-ef75-4f99-b3e8-30e51331c6df', 'Steel companies can access climate finance through green bonds and transition finance.', '[{"question": "What climate finance is available?", "answer": "Green bonds, transition bonds, DFI loans."}, {"question": "What do investors look for?", "answer": "Science-based targets and credible transition plans."}]', '{"introduction": "Steel requires $1.4 trillion for net-zero transition.", "main_content": "## Investment Readiness\n\n### Transition Strategy\nScience-aligned targets.\n\n### Project Pipeline\nBankable projects with clear economics."}', '[{"url": "/decarbonisation-steel-industry", "title": "Decarbonisation for Steel"}]'),

-- Climate Investment × Cement
('climate-investment-cement', 'Climate Investment for Cement Industry | Bombay Breed', 'Access green finance for cement decarbonisation.', 'Climate Investment Readiness for Cement Industry', 'combined', true, 70, '4a3007bc-d5a8-4e43-acba-640d1dd33e5f', 'c8355272-2a85-49c6-9ba8-2145924d2daf', 'Cement companies can unlock transition finance through sustainability-linked bonds.', '[{"question": "What makes cement projects bankable?", "answer": "Clear baseline, proven technology, offtake certainty."}, {"question": "Are sustainability-linked bonds suitable?", "answer": "Yes, with KPIs tied to emission intensity."}]', '{"introduction": "Cement decarbonisation requires significant capital.", "main_content": "## Finance Pathways\n\n### Green Bonds\nFor renewable and WHR projects.\n\n### Transition Finance\nFor alternative fuel infrastructure."}', '[{"url": "/decarbonisation-cement-industry", "title": "Decarbonisation for Cement"}]'),

-- DMRV × Steel
('dmrv-steel-industry', 'MRV for Steel Decarbonisation | Bombay Breed', 'Implement MRV systems for steel emission reductions and carbon credit projects.', 'MRV Systems for Steel Industry', 'combined', true, 65, '7ee0fc75-660c-40ac-b13b-e5079b30735d', '635fa88b-ef75-4f99-b3e8-30e51331c6df', 'Steel MRV must track Scope 1, 2, 3 emissions following GHG Protocol and ResponsibleSteel.', '[{"question": "What standards apply?", "answer": "GHG Protocol, ResponsibleSteel, ISO 14064."}, {"question": "How is intensity measured?", "answer": "Tonnes CO2e per tonne crude steel."}]', '{"introduction": "Credible MRV is foundational for steel decarbonisation claims.", "main_content": "## MRV Framework\n\n### Data Management\nAutomated data collection.\n\n### Third-Party Verification\nAnnual verification by accredited bodies."}', '[{"url": "/decarbonisation-steel-industry", "title": "Decarbonisation for Steel"}]'),

-- DMRV × Cement
('dmrv-cement-industry', 'MRV for Cement Decarbonisation | Bombay Breed', 'Implement MRV systems for cement emission reductions following GCCA standards.', 'MRV Systems for Cement Industry', 'combined', true, 65, '7ee0fc75-660c-40ac-b13b-e5079b30735d', 'c8355272-2a85-49c6-9ba8-2145924d2daf', 'Cement MRV covers process emissions and fuel combustion per GCCA protocol.', '[{"question": "What is GCCA protocol?", "answer": "Standardized approach to measuring cement sector emissions."}, {"question": "How are process emissions measured?", "answer": "Based on clinker production and raw material composition."}]', '{"introduction": "Cement requires specialized MRV for process and combustion emissions.", "main_content": "## MRV Requirements\n\n### Process Emissions\nCalculate from clinker production.\n\n### Intensity Metrics\nCO2 per tonne cementitious product."}', '[{"url": "/decarbonisation-cement-industry", "title": "Decarbonisation for Cement"}]');