// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjiwmdrtuhsrymsuvpfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqaXdtZHJ0dWhzcnltc3V2cGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Mzk3NzYsImV4cCI6MjA3MjMxNTc3Nn0.6D8BOkjFNNbEzKqAgElZvS8Ki8hezTqjpQpBk-og6do";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});